// AUTH
export const IS_LOADING = "IS_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_PROFILE = "SET_USER_PROFILE";

// PROFILE
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const UPDATE_TROOPS_SUCCESS = "UPDATE_TROOPS_SUCCESS";
export const UPDATE_TROOPS_ERROR = "UPDATE_TROOPS_ERROR";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const IMG_SUCCESS = "IMG_SUCCESS";
export const IMG_ERROR = "IMG_ERROR";

// ALLIANCE
export const GET_ALLIANCE_SUCCESS = "GET_ALLIANCE_SUCCESS";
export const GET_ALLIANCE_ERROR = "GET_ALLIANCE_ERROR";
export const GET_ALLIANCE_LIST_SUCCESS = "GET_ALLIANCE_LIST_SUCCESS";
export const GET_ALLIANCE_LIST_ERROR = "GET_ALLIANCE_LIST_ERROR";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_MEMBERS_ERROR = "GET_MEMBERS_ERROR";
export const CREATE_ALLIANCE_SUCCESS = "CREATE_ALLIANCE_SUCCESS";
export const CREATE_ALLIANCE_ERROR = "CREATE_ALLIANCE_ERROR";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_ERROR = "GET_APPLICATIONS_ERROR";
export const SEND_APPLICATION_SUCCESS = "SEND_APPLICATION_SUCCESS";
export const SEND_APPLICATION_ERROR = "SEND_APPLICATION_ERROR";
export const CANCEL_APP_SUCCESS = "CANCEL_APP_SUCCESS";
export const CANCEL_APP_ERROR = "CANCEL_APP_ERROR";
export const GET_PRIVILEGE_SUCCESS = "GET_PRIVILEGE_SUCCESS";
export const GET_PRIVILEGE_ERROR = "GET_PRIVILEGE_ERROR";
export const ALLIANCE_SETTINGS_SUCCESS = "ALLIANCE_SETTINGS_SUCCESS";
export const ALLIANCE_SETTINGS_ERROR = "ALLIANCE_SETTINGS_ERROR";
export const DELETE_ALLIANCE_SUCCESS = "DELETE_ALLIANCE_SUCCESS";
export const DELETE_ALLIANCE_ERROR = "DELETE_ALLIANCE_ERROR";
export const GET_APPS_SUCCESS = "GET_APPS_SUCCESS";
export const GET_APPS_ERROR = "GET_APPS_ERROR";
export const ACCEPT_APP_SUCCESS = "ACCEPT_APP_SUCCESS";
export const ACCEPT_APP_ERROR = "ACCEPT_APP_ERROR";

// EVENTS
export const GET_CURRENT_EVENTS_SUCCESS = "GET_CURRENT_EVENTS_SUCCESS";
export const GET_CURRENT_EVENTS_ERROR = "GET_CURRENT_EVENTS_ERROR";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_ERROR = "CREATE_EVENTS_ERROR";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_ERROR = "DELETE_EVENT_ERROR";
export const WILL_PARTICIPATE_SUCCESS = "WILL_PARTICIPATE_SUCCESS";
export const WILL_PARTICIPATE_ERROR = "WILL_PARTICIPATE_ERROR";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_ERROR = "GET_ALL_EVENTS_ERROR";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_ERROR = "GET_EVENT_ERROR";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_ERROR = "CREATE_TEAM_ERROR";
export const INIT_CHOICE_SUCCESS = "INIT_CHOICE_SUCCESS";
export const INIT_CHOICE_ERROR = "INIT_CHOICE_ERROR";
export const PARTICIPATING_EVENTS_SUCCESS = "PARTICIPATING_EVENTS_SUCCESS";
export const PARTICIPATING_EVENTS_ERROR = "PARTICIPATING_EVENTS_ERROR";
export const UPDATE_TEAMS_SUCCESS = "UPDATE_TEAMS_SUCCESS";
export const UPDATE_TEAMS_ERROR = "UPDATE_TEAMS_ERROR";
