// AUTH
export const IS_LOADING = "IS_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_PROFILE = "SET_USER_PROFILE";

// PROFILE
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const UPDATE_TROOPS_SUCCESS = "UPDATE_TROOPS_SUCCESS";
export const UPDATE_TROOPS_ERROR = "UPDATE_TROOPS_ERROR";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const GET_IMG_SUCCESS = "GET_IMG_SUCCESS";
export const GET_IMG_ERROR = "GET_IMG_ERROR";
export const IMG_SUCCESS = "IMG_SUCCESS";
export const IMG_ERROR = "IMG_ERROR";

// ALLIANCE
export const GET_ALLIANCE_SUCCESS = "GET_ALLIANCE_SUCCESS";
export const GET_ALLIANCE_ERROR = "GET_ALLIANCE_ERROR";
export const GET_ALLIANCE_LIST_SUCCESS = "GET_ALLIANCE_LIST_SUCCESS";
export const GET_ALLIANCE_LIST_ERROR = "GET_ALLIANCE_LIST_ERROR";
export const CREATE_ALLIANCE_SUCCESS = "CREATE_ALLIANCE_SUCCESS";
export const CREATE_ALLIANCE_ERROR = "CREATE_ALLIANCE_ERROR";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_ERROR = "GET_APPLICATIONS_ERROR";
export const SEND_APPLICATION_SUCCESS = "SEND_APPLICATION_SUCCESS";
export const SEND_APPLICATION_ERROR = "SEND_APPLICATION_ERROR";
export const CANCEL_APP_SUCCESS = "CANCEL_APP_SUCCESS";
export const CANCEL_APP_ERROR = "CANCEL_APP_ERROR";

// EVENTS
export const GET_CURRENT_EVENTS_SUCCESS = "GET_CURRENT_EVENTS_SUCCESS";
export const GET_CURRENT_EVENTS_ERROR = "GET_CURRENT_EVENTS_ERROR";
